### PR TITLE
Create package list on package load/unload

### LINKED ISSUE #12: Installing a package via the ui should update packages.cson

### PR DESCRIPTION
**Pull request by jbhannah**
Fixes #12. I've been using something like this in [my `init.coffee`](https://github.com/jbhannah/dotfiles/blob/d9b5943f64c65fd63ffbd869db6e799fdc3271d4/atom/init.coffee) to maintain a simple package list.

### CODE REVIEW

**Comment by lee-dohm** [comment]
Thanks for this!

**Comment by lee-dohm** [comment]
On deeper inspection, there are some potential flaws in this implementation:

* The `package-sync.forceOverwrite` option has to be enabled for this to work
* This could cause serious performance issues on startup since every time any package is loaded, the entire packages list is generated again

**Comment by jbhannah** [comment]
`onDidLoadPackage` and `onDidUnloadPackage` only fire when a package is installed or uninstalled (tested by `console.log`ging in the callback function), not individually for every package, so it shouldn't have an additional performance impact. The first point is a known issue, but behavior with that option disabled should still be consistent.

**Comment by lee-dohm** [comment]
To test our respective theories I added this line:

```coffee
fs.appendFileSync("/Users/lee-dohm/package.log", pack.name + "\n", "utf8")
```

to `PackageManager.loadPackage` immediately after the `@emitter.emit 'did-load-package', pack` line. Then I compiled, launched, and exited Atom. Here is the resulting file:

```
advanced-open-file
atomic-chrome
bug-report
file-type-icons
indentation-indicator
language-elixir
minimap
red-wavy-underline
set-syntax
soft-wrap-indicator
sort-lines
tabs-to-spaces
toggle-quotes
atom-dark-syntax
atom-dark-ui
atom-light-syntax
atom-light-ui
base16-tomorrow-dark-theme
base16-tomorrow-light-theme
one-dark-ui
one-light-ui
one-dark-syntax
one-light-syntax
solarized-dark-syntax
solarized-light-syntax
about
archive-view
autocomplete-atom-api
autocomplete-css
autocomplete-html
autocomplete-plus
autocomplete-snippets
autoflow
autosave
background-tips
bookmarks
bracket-matcher
command-palette
deprecation-cop
dev-live-reload
encoding-selector
exception-reporting
fuzzy-finder
git-diff
find-and-replace
go-to-line
grammar-selector
image-view
incompatible-packages
keybinding-resolver
line-ending-selector
link
markdown-preview
metrics
notifications
open-on-github
package-generator
settings-view
snippets
spell-check
status-bar
styleguide
symbols-view
tabs
timecop
tree-view
update-package-dependencies
welcome
whitespace
wrap-guide
language-c
language-clojure
language-coffee-script
language-csharp
language-css
language-gfm
language-git
language-go
language-html
language-hyperlink
language-java
language-javascript
language-json
language-less
language-make
language-mustache
language-objective-c
language-perl
language-php
language-property-list
language-python
language-ruby
language-ruby-on-rails
language-sass
language-shellscript
language-source
language-sql
language-text
language-todo
language-toml
language-xml
language-yaml
```

So, `onDidLoadPackage` fires for every package that is loaded, including during startup.

I sincerely apologize but because of this I have to revert this change.

**Comment by jbhannah** [comment]
I see what's going on: `init.coffee` runs [after all packages are loaded on startup](https://github.com/atom/atom/blob/4d52479ce3549cd646527bea8f754b8b21887cb7/src/atom-environment.coffee#L684), so when the callback is registered in `init.coffee` it will only fire when new packages are loaded. You're right that, by putting it in a package, it will fire for all packages that are loaded after this package. I can't find another event that fires after the initial package load that it would make sense to add a listener for that then registers the callback; that's the only other way I can think of to accomplish the same thing.

**Comment by jbhannah** [comment]
Maybe `onDidActivateInitialPackages`. Trying now.

**Pull request merged**
