### PR TITLE
Fix deprecations

### PR DESCRIPTION
**Pull request by postcasio**
Still need to update specs, don't merge yet.

### CODE REVIEW

**Comment by postcasio** [comment]
I'd be happy to take this over btw, I still use it myself.

**Comment by lee-dohm** [comment]
Cool ... I'll add you as a collaborator! Do you know if that will allow you to publish to https://atom.io/packages also?

**Comment by postcasio** [comment]
```
Preparing and tagging a new version ✓
Pushing v0.1.2 tag ✓
Publishing package-sync@v0.1.2 ✗
Creating new version failed: Git tag not found
```

Apparently not...

**Comment by lee-dohm** [comment]
Ok, I pushed this one. I'll see what I have to do to give you publish permissions.

**Pull request merged**
