### PR TITLE
Add option to support overwriting packages.cson

### PR DESCRIPTION
**Pull request by czchen**

### CODE REVIEW

**Comment by lee-dohm** [comment]
Could you add some specs for this?

**Comment by czchen** [comment]
Not sure if the following is the spec needed:

A new option `forceOverwrite` is added, it is `boolean` with default value `false`.

*   When `forceOverwrite` set to `true`, `package-sync:create-package-list` will always create `packages.cson`, whether it is present or not.

*   When `forceOverwrite` set to `false`, `package-sync:create-package-list` will create `packages.cson` only when it is absense.

**Comment by lee-dohm** [comment]
The first case is needed. The second case is already tested.

**Comment by czchen** [comment]
Test case is implemented in 8b259ec44b79ab1e5c9e4e1926bb35f5b300572b. Please help to review it.

**Comment by lee-dohm** [comment]
Looks good! Thanks for contributing :grinning:

**Pull request merged**
